#!/bin/bash
function die () {
  echo 1>&2 "${1}"
  exit 1
}

if [[ -z "$(which ffmpeg)" ]] ; then
  die "ffmpeg not found"
fi
if [[ -z "$(which mediainfo)" ]] ; then
  die "mediainfo not found"
fi
if [[ -z "$(which java)" ]] ; then
  die "java not found"
fi

SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
cd "${SCRIPT_DIR}" || die "Error changing into directory: ${SCRIPT_DIR}"

JVC="$(which jvc)"
if [[ -z "${JVC}" ]] ; then
  JVC_REPO="https://github.com/getbubblenow/javicle.git"
  echo "jvc command not found"
  if [[ ! -d javicle ]] ; then
    echo "cloning: ${JVC_REPO}"
    git clone ${JVC_REPO} || die "Error cloning repository: ${JVC_REPO}"
  fi
  pushd javicle || die "pushd error"
  if [[ -z "$(which mvn)" ]] ; then
    die "mvn not found"
  fi
  ./bin/jvc --help > /dev/null 2>&1
  popd || die "popd error"
fi
export PATH=${PATH}:${SCRIPT_DIR}/javicle/bin
JVC="$(which jvc)"
if [[ -z "${JVC}" ]] ; then
  die "jvc command not found even after building jvc jar"
fi

mkdir -p output || die "Error creating output directory"

# Re-create build_screencast.mp4
BUILD_SCREENCAST_SRC=assets/build_screencast.mp4
if [[ ! -f "${BUILD_SCREENCAST_SRC}" ]] ; then
  cat ${BUILD_SCREENCAST_SRC}.1 ${BUILD_SCREENCAST_SRC}.2 > ${BUILD_SCREENCAST_SRC} || die "re-creating ${BUILD_SCREENCAST_SRC}"
fi

# Re-create iphone_07_operations.mp4
IPHONE_SLIDE_7=assets/iphone_07_operations.mp4
if [[ ! -f "${IPHONE_SLIDE_7}" ]] ; then
  cat ${IPHONE_SLIDE_7}.1 ${IPHONE_SLIDE_7}.2 > ${IPHONE_SLIDE_7} || die "re-creating ${IPHONE_SLIDE_7}"
fi

# Slide 1
jtrim assets/iphone_01_intro.mp4 output/iphone_01_intro_trimmed.mp4 3.1 17.8 || die "jtrim 1"
jkenburns assets/jvc-slides01.png output/slide_01.mp4 16 || die "jkenburns 1"

# Slide 2
jtrim assets/iphone_02_why.mp4 output/iphone_02_why_trimmed.mp4 1.3 50.3 || die "jtrim 2"
jkenburns assets/jvc-slides02.png output/slide_02.mp4 50 || die "jkenburns 2"

# Slide 3
jtrim assets/iphone_03_why.mp4 output/iphone_03_why_trimmed.mp4 1.1 90 || die "jtrim 3"
jkenburns assets/jvc-slides03.png output/slide_03.mp4 91 || die "jkenburns 3"

# Slide 4
jtrim assets/iphone_04_build.mp4 output/iphone_04_build_trimmed.mp4 1.2 27.8 || die "jtrim 4"
jkenburns assets/jvc-slides04.png output/slide_04.mp4 27.6 || die "jkenburns 4"

# Slide 5
jtrim assets/iphone_05_build.mp4 output/iphone_05_build_trimmed.mp4 1.8 37.5 || die "jtrim 5"
jkenburns assets/jvc-slides05.png output/slide_05.mp4 37 || die "jkenburns 5"

# Slide 6
jtrim assets/iphone_06_run.mp4 output/iphone_06_run_trimmed.mp4 1 72 || die "jtrim 6"
jkenburns assets/jvc-slides06.png output/slide_06.mp4 72 || die "jkenburns 6"

# Slide 7
jtrim "${IPHONE_SLIDE_7}" output/iphone_07_operations_trimmed.mp4 1.7 116 || die "jtrim 7"
jkenburns assets/jvc-slides07.png output/slide_07.mp4 117.5 || die "jkenburns 7"

# Slide 8
jtrim assets/iphone_08_making_of.mp4 output/iphone_08_making_of_trimmed.mp4 6.5 37.5 || die "jtrim 8"
jkenburns assets/jvc-slides08.png output/slide_08.mp4 32 || die "jkenburns 8"

# Slide 9
jtrim assets/iphone_09_end.mp4 output/iphone_09_end_trimmed.mp4 3.2 30.5 || die "jtrim 9"
jkenburns assets/jvc-slides01.png output/slide_09.mp4 28 || die "jkenburns 9"

# Speed up "clone and build" video so that it runs for 28 seconds
BUILD_VID=output/build.mp4
jspeed "${BUILD_SCREENCAST_SRC}" "${BUILD_VID}" "source.duration / 28"

# Add overlays
jvc overlays.jvc || die "overlays"

# Concat it all together
FINAL_VIDEO="$(pwd)"/jvc-vid.mp4
jconcat "${FINAL_VIDEO}" $(ls -1 output/overlay*.mp4) || die "concat"

echo "Successfully created: ${FINAL_VIDEO}"